const dummyGS6 = {
  id: 1,
  narasisoal: "GS6 - JURNAL KAS KELUAR",
  cvname: "CV Rofadi",
  cvalamat: "Jl. Soekarno Blok A1, Malang",
  tblworkname: "BULAN DESEMBER 2021",
  introsoal:
    "Berikut ini merupakan data Harga Pokok Penjualan untuk beberapa produk pada saat tanggal transaksi terjadi yang bersumber dari Kartu Persediaan:",
  introkontan:
    "Transaksi penjualan tunai yang terjadi selama bulan Desember 2021  sebagai berikut.",
  introkas:
    "Transaksi pelunasan piutang yang terjadi selama bulan Desember 2021  sebagai berikut.",
  datanota: [
    {
      id: 1,
      id_config: 1,
      uid: "123abc",
      type: "kontan",
      no: "K91221",
      tgl: "9/12/2021",
      subtotal: 4550000,
      ppn: 455000,
      total: 5005000,
      penerima: "PT. TJIWI BIOO",
      keperluan: "Pembelian tunai",
      nilaih: 0,
      nilaia: 0,
      alamat: "Jl. Jakarta 19 Malang",
      keterangan: "Pembelian tunai",
    },
    {
      id: 2,
      id_config: 1,
      uid: "456abc",
      type: "kas",
      no: "K11207",
      tgl: "15/12/2021",
      subtotal: 0,
      ppn: 0,
      total: 6000000,
      penerima: "Karyawan",
      keperluan: "Gaji Desember 2021",
      nilaih: "Enam juta rupiah",
      nilaia: 6000000,
      alamat: "",
      keterangan: "Pembayaran gaji karyawan",
    },
  ],
  databarang: [
    {
      id: 1,
      id_config: 1,
      uid: "123abc",
      namabarang: "Light F4 70gr",
      jumlah: 75,
      harga: 50000,
      total: 3750000,
      hpp: 50000,
    },
    {
      id: 2,
      id_config: 1,
      uid: "123abc",
      namabarang: "Concorde A4 220gr",
      jumlah: 100,
      harga: 8000,
      total: 800000,
      hpp: 8000,
    },
  ],
  dataakun: [
    {
      id: 1,
      id_config: 1,
      noakun: 110,
      jumlah: 11005000,
      posisi: "kredit",
      name: "kas",
    },
    {
      id: 2,
      id_config: 1,
      noakun: 115,
      jumlah: 4550000,
      posisi: "debit",
      name: "persediaan",
    },
    {
      id: 3,
      id_config: 1,
      noakun: 116,
      jumlah: 455000,
      posisi: "debit",
      name: "ppnmasukan",
    },
    {
      id: 4,
      id_config: 1,
      noakun: 620,
      jumlah: 6000000,
      posisi: "debit",
      name: "bebangaji",
    },
  ],
};

export default dummyGS6;
