// ─── Master Dropdown — Lampiran 4 ──────────────────────────────────────────────
// File ini HANYA menyimpan master data (Tax Object & Type Of Income) untuk L4.
// Tidak ada business rule, state management, atau helper di file ini.
// L4.js meng-import array di bawah ini apa adanya.
//
// PENTING: Urutan setiap array WAJIB dipertahankan — jangan diurutkan ulang.

// ─── BAGIAN A — Tax Object ─────────────────────────────────────────────────────
export const TAX_OBJECT_OPTIONS = [
    { value: '',    label: 'Please Select' },
    { value: 'TO01', label: 'Penghasilan Sehubungan dengan Transaksi Penjualan Barang, Penyerahan Jasa, dan/atau Persewaan serta Penghasilan Lain Sehubungan dengan Penggunaan Harta yang Dilakukan Melalui Pihak Lain dalam Sistem Informasi Pengadaan Pemerintah' },
    { value: 'TO02', label: 'Penghasilan yang Diterima atau Diperoleh Pedagang Dalam Negeri Penjualan Barang, Penyerahan Jasa, dan/atau Persewaan serta Penghasilan Lain Sehubungan dengan Penggunaan Harta yang Dilakukan Melalui Perdagangan Melalui Sistem Elektronik' },
    { value: 'TO03', label: 'Penjualan BBM oleh Pertamina atau Anak Perusahaan Pertamina Kepada SPBU (Final)' },
    { value: 'TO04', label: 'Penjualan BBM oleh Badan Usaha Selain Pertamina atau Anak Perusahaan Pertamina Kepada SPBU/Agen/Penyalur (Final)' },
    { value: 'TO05', label: 'Penjualan BBG oleh produsen/importir Kepada SPBU/Agen/Penyalur (Final)' },
    { value: 'TO06', label: 'Penjualan BBM oleh Pertamina atau Anak Perusahaan Pertamina kepada Agen/Penyalur selain SPBU (Final)' },
    { value: 'TO07', label: 'Penghasilan Sehubungan dengan Aset Kripto yang dipungut oleh Penyelenggara Perdagangan Melalui Sistem Elektronik yang Merupakan Pedagang Fisik Aset Kripto' },
    { value: 'TO08', label: 'Penghasilan Sehubungan dengan Aset Kripto yang dipungut oleh Penyelenggara Perdagangan Melalui Sistem Elektronik yang Bukan Merupakan Pedagang Fisik Aset Kripto' },
    { value: 'TO09', label: 'Penghasilan Sehubungan dengan Aset Kripto (Setor Sendiri)' },
    { value: 'TO10', label: 'Bunga Obligasi, Surat Utang Negara, atau Obligasi Daerah yang Diterima Wajib Pajak Dalam Negeri dan Bentuk Usaha Tetap' },
    { value: 'TO11', label: 'Bunga Obligasi yang Diterima Wajib Pajak Dalam Negeri dan Bentuk Usaha Tetap yang diadministrasikan oleh BI' },
    { value: 'TO12', label: 'Diskonto Surat Perbendaharaan Negara yang Diterima Wajib Pajak Dalam Negeri dan Bentuk Usaha Tetap' },
    { value: 'TO13', label: 'Diskonto Surat Perbendaharaan Negara yang Diterima Wajib Pajak Penduduk/Berkedudukan di Luar Negeri' },
    { value: 'TO14', label: 'Bunga Obligasi yang Diterima Wajib Pajak Dalam Negeri dan Bentuk Usaha Tetap' },
    { value: 'TO15', label: 'Pengalihan Hak atas Tanah dan/atau Bangunan' },
    { value: 'TO16', label: 'Pengalihan Rumah Sederhana dan Rumah Susun Sederhana yang Dilakukan oleh WP yang Usaha Pokoknya Mengalihkan Hak atas Tanah dan/atau Bangunan' },
    { value: 'TO17', label: 'Pengalihan Hak atas Tanah dan/atau Bangunan kepada Pemerintah, BUMN yang Mendapat Penugasan Khusus dari Pemerintah, atau BUMD yang Mendapat Penugasan Khusus dari Kepala Daerah, sesuai UU mengenai Pengadaan Tanah bagi Pembangunan untuk Kepentingan Umum' },
    { value: 'TO18', label: 'Persewaan Tanah dan/atau Bangunan' },
    { value: 'TO19', label: 'Bunga Tabungan dan Bunga Deposito yang Ditempatkan di Dalam Negeri yang Dananya Bersumber Selain dari Devisa Hasil Ekspor (DHE)' },
    { value: 'TO20', label: 'Bunga Deposito yang Ditempatkan di Dalam Negeri (mata uang IDR bersumber dari DHE tenor 1 bulan)' },
    { value: 'TO21', label: 'Bunga Deposito yang Ditempatkan di Dalam Negeri (mata uang IDR bersumber dari DHE tenor 3 bulan)' },
    { value: 'TO22', label: 'Bunga Deposito yang Ditempatkan di Dalam Negeri (mata uang IDR bersumber dari DHE tenor 6 bulan atau lebih)' },
    { value: 'TO23', label: 'Bunga Deposito yang Ditempatkan di Dalam Negeri (mata uang USD bersumber dari DHE tenor 1 bulan)' },
    { value: 'TO24', label: 'Bunga Deposito yang Ditempatkan di Dalam Negeri (mata uang USD bersumber dari DHE tenor 3 bulan)' },
    { value: 'TO25', label: 'Bunga Deposito yang Ditempatkan di Dalam Negeri (mata uang USD bersumber dari DHE tenor 6 bulan)' },
    { value: 'TO26', label: 'Bunga Deposito yang Ditempatkan di Dalam Negeri (mata uang USD bersumber dari DHE tenor lebih 6 bulan)' },
    { value: 'TO27', label: 'Bunga Deposito/Tabungan yang Ditempatkan di Luar Negeri Melalui Bank yang Didirikan atau Bertempat Kedudukan di Indonesia atau Cabang Bank Luar Negeri di Indonesia' },
    { value: 'TO28', label: 'Diskonto Sertifikat Bank Indonesia' },
    { value: 'TO29', label: 'Jasa Giro' },
    { value: 'TO30', label: 'Hadiah Undian' },
    { value: 'TO31', label: 'Transaksi Penjualan Saham di Bursa Efek (Bukan Saham Pendiri)' },
    { value: 'TO32', label: 'Transaksi Penjualan Saham di Bursa Efek (Saham Pendiri)' },
    { value: 'TO33', label: 'Transaksi Penjualan Saham Milik Perusahaan Modal Ventura Tidak di Bursa Efek' },
    { value: 'TO34', label: 'Jasa Konstruksi Berupa Jasa Perencanaan Konstruksi (Dengan Kualifikasi Usaha)' },
    { value: 'TO35', label: 'Jasa Konstruksi Berupa Jasa Perencanaan Konstruksi (Tanpa Kualifikasi Usaha)' },
    { value: 'TO36', label: 'Jasa Konstruksi Berupa Jasa Pelaksanaan Konstruksi (Kualifikasi Usaha Kecil)' },
    { value: 'TO37', label: 'Jasa Konstruksi Berupa Jasa Pelaksanaan Konstruksi (Kualifikasi Usaha Menengah dan Besar)' },
    { value: 'TO38', label: 'Jasa Konstruksi Berupa Jasa Pelaksanaan Konstruksi (Tanpa Kualifikasi Usaha)' },
    { value: 'TO39', label: 'Jasa Konstruksi Berupa Jasa Pengawasan Konstruksi (Dengan Kualifikasi Usaha)' },
    { value: 'TO40', label: 'Jasa Konstruksi Berupa Jasa Pengawasan Konstruksi (Tanpa Kualifikasi Usaha)' },
    { value: 'TO41', label: 'Pekerjaan Konstruksi yang Dilakukan oleh Penyedia Jasa yang Memiliki Sertifikat Badan Usaha Kualifikasi Kecil atau Sertifikat Kompetensi Kerja untuk Usaha Orang Perseorangan' },
    { value: 'TO42', label: 'Pekerjaan Konstruksi yang Dilakukan oleh Penyedia Jasa yang Tidak Memiliki Sertifikat Badan Usaha Atau Sertifikat Kompetensi Kerja untuk Usaha Orang Perseorangan' },
    { value: 'TO43', label: 'Pekerjaan Konstruksi yang Dilakukan oleh Penyedia Jasa yang Memiliki Sertifikat Selain Sertifikat Badan Usaha Kualifikasi Kecil atau Sertifikat Kompetensi Kerja untuk Usaha Orang Perseorangan' },
    { value: 'TO44', label: 'Pekerjaan Konstruksi Terintegrasi yang Dilakukan oleh Penyedia Jasa yang Memiliki Sertifikat Badan Usaha' },
    { value: 'TO45', label: 'Pekerjaan Konstruksi Terintegrasi yang Dilakukan oleh Penyedia Jasa yang Tidak Memiliki Sertifikat Badan Usaha' },
    { value: 'TO46', label: 'Jasa Konsultansi Konstruksi yang Dilakukan oleh Penyedia Jasa yang Memiliki Sertifikat Badan Usaha atau Sertifikat Kompetensi Kerja untuk Usaha Orang Perseorangan' },
    { value: 'TO47', label: 'Jasa Konsultansi Konstruksi yang Dilakukan oleh Penyedia Jasa yang Tidak Memiliki Sertifikat Badan Usaha atau Sertifikat Kompetensi Kerja untuk Usaha Orang Perseorangan' },
    { value: 'TO48', label: 'Imbalan yang Diterima/Diperoleh Sehubungan dengan Pengangkutan Orang dan/atau Barang Termasuk Penyewaan Kapal Laut Oleh Perusahaan Pelayaran Dalam Negeri' },
    { value: 'TO49', label: 'Imbalan yang Dibayarkan/Terutang kepada Perusahaan Pelayaran Dalam Negeri' },
    { value: 'TO50', label: 'Imbalan yang Dibayarkan/Terutang kepada Perusahaan Pelayaran dan/atau Penerbangan Luar Negeri Sehubungan dengan Pengangkutan Orang dan/atau Barang (Selain Berdasarkan Perjanjian Charter)' },
    { value: 'TO51', label: 'Imbalan Charter Kapal Laut dan/atau Pesawat Udara yang Dibayarkan/Terutang kepada Perusahaan Pelayaran dan/atau Penerbangan Luar Negeri melalui BUT di Indonesia' },
    { value: 'TO52', label: 'Penghasilan Wajib Pajak Luar Negeri yang Mempunyai Kantor Perwakilan Dagang di Indonesia' },
    { value: 'TO53', label: 'Revaluasi atau penilaian kembali aset tetap' },
    { value: 'TO54', label: 'Bunga Simpanan yang Dibayarkan oleh Koperasi kepada Anggota Wajib Pajak Orang Pribadi (bunga sampai dengan Rp240.000,00)' },
    { value: 'TO55', label: 'Bunga Simpanan yang Dibayarkan oleh Koperasi kepada Anggota Wajib Pajak Orang Pribadi (bunga di atas Rp240.000,00)' },
    { value: 'TO56', label: 'Dividen yang Diterima/Diperoleh Wajib Pajak Orang Pribadi Dalam Negeri' },
    { value: 'TO57', label: 'Uplift Hulu Migas' },
    { value: 'TO58', label: 'Participating Interest Eksplorasi Hulu Migas' },
    { value: 'TO59', label: 'Participating Interest Eksploitasi Hulu Migas' },
    { value: 'TO60', label: 'Transaksi dengan Wajib Pajak yang menggunakan tarif Peraturan Pemerintah Nomor 23 Tahun 2018' },
    { value: 'TO61', label: 'Transaksi dengan Wajib Pajak yang menggunakan tarif Peraturan Pemerintah Nomor 55 Tahun 2022' },
    { value: 'TO62', label: 'Penghasilan yang dikenakan pajak bersifat final sesuai Peraturan Pemerintah Nomor 23/55 (Disetor Sendiri)' },
    { value: 'TO63', label: 'Perjanjian Pengikatan Jual Beli' },
    { value: 'TO64', label: 'Penghasilan Wajib Pajak yang Melakukan Kegiatan Usaha Jasa Maklon (Contract Manufacturing) Internasional di Bidang Produksi Mainan Anak-Anak' },
    { value: 'TO65', label: 'Penghasilan yang Diterima atau Diperoleh Sehubungan dengan Kerja Sama dengan Lembaga Pengelola Investasi (LPI)' },
    { value: 'TO66', label: 'Penghasilan Final Lainnya' },
];

// ─── BAGIAN B — Type Of Income ─────────────────────────────────────────────────
// Setiap entry memiliki value (raw input, dipersist), label (ditampilkan),
// dan code (derived — TIDAK dipersist, di-derive ulang setiap render oleh L4.js).
export const TYPE_OF_INCOME_OPTIONS = [
    { value: '',     label: 'Please Select', code: '' },
    { value: 'C001', label: 'Penghasilan tertentu bagi BPKH', code: 'C001' },
    { value: 'C002', label: 'Penghasilan tertentu bagi BPJS', code: 'C002' },
    { value: 'C003', label: 'Iuran dan Penghasilan tertentu yang menerima dana pensiun', code: 'C003' },
    { value: 'C004', label: 'Penghasilan untuk pembangunan dan pengadaan sarana dan prasarana', code: 'C004' },
    { value: 'C005', label: 'Dividen atau bagian laba', code: 'C005' },
    { value: 'C006', label: 'Bagian laba yang diterima perusahaan modal ventura dari badan pasangan usaha', code: 'C006' },
    { value: 'C007', label: 'Pembebasan utang', code: 'C007' },
    { value: 'C008', label: 'Hibah', code: 'C008' },
    { value: 'C009', label: 'Bantuan/Sumbangan', code: 'C009' },
    { value: 'C010', label: 'Bagian Laba Anggota Perseroan Komanditer Tidak Atas Saham, Persekutuan, Perkumpulan, Firma, Kongsi', code: 'C010' },
    { value: 'C011', label: 'Klaim asuransi kesehatan, kecelakaan, jiwa, dwiguna, beasiswa', code: 'C011' },
    { value: 'C012', label: 'Hadiah langsung yang diberikan kepada semua pembeli/konsumen akhir tanpa diundi', code: 'C012' },
    { value: 'C013', label: 'Harta termasuk setor tunai yang diterima oleh badan sebagai pengganti saham atau pengganti penyertaan modal', code: 'C013' },
    { value: 'C014', label: 'Penghasilan lain yang tidak termasuk objek pajak', code: 'C014' },
];